export const CART_ACTION_TYPES = {
	TOGGLE_CART_OPEN: "cart/TOGGLE_CART_OPEN",
	ADD_CART_ITEMS: "cart/ADD_CART_ITEMS",
	REMOVE_CART_ITEMS: "cart/REMOVE_CART_ITEMS",
	CLEAR_CART_ITEMS: "cart/CLEAR_CART_ITEMS",
};
